version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: gauntlet_ai_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gauntlet_ai_db
    ports:
      - "5433:5432"  # Changed host port to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: